@startuml map

class cutscenes {
    cutscene1()
}


class main {
    runGame()
}

class choices {

}

class game {
    {static} Game Constructor:
        self.game.username
    ..Big methods..
    menu()
    disclaimer()
    startGame([call cutscene1])
    endGame()
}

package UI <<frame>> {
    class window {
        {static} Window Constructor
            self.window
            self.window.title
            self.window.geometry
            self.window.configure
        .. Methods ..
        makeFrame()
        makeLabel()
        makeButton()
        makeInput()
        ..Functions..
    }
    class image {
        {static} Image Constructor
            self.canvas
            self.canvas.pack
        .. Methods ..
        insertImage()
    }

    class animated {
        {static} animated Constructor:

        ..Methods..
        runningRight()
        walkingRight()
        runningLeft()
        walkingLeft()
        runningUp()
        walkingUp()
        runningDown()
        walkingDown()
    }
}

main <-- choices
main <-- game

game *- cutscenes

cutscenes *-- animated

game *-- window
cutscenes <-- image

@enduml